### ISSUE TITLE
Better detection of Timeline Playback State

### ISSUE THREAD

**Issue by latenitefilms** [CommandPost/CommandPost#64]
Currently we don't really know for certain if the timeline is playing back or not.

This means that if you enable the Scrolling Timeline whilst the timeline is currently playing back, the script will get confused, and it will think things are playing back whilst they're stopped and vice-versa. You'll then need to disable the Scrolling Timeline and re-enable to fix.

The only way I can think of solving this is by writing a watcher that constantly monitors the timecode window for changes.

**Comment by latenitefilms** [comment]
This might be a job for @randomeizer ?

**Comment by randomeizer** [comment]
I don't think it's going to be possible to reliably determine if the timeline is playing. It is possible to tell if it is stopped - you just check that the playhead position hasn't changed for some amount of time. But the reverse is more complicated unfortunately.

In the meantime, I've added a Playhead Lock feature which achieves a similar result in a different way. Instead of scrolling the timeline when playing, it always locks the playhead to the middle of the timeline view. It can be enabled/disabled with a shortcut.
